import { NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";
import { existsSync } from "fs";

// Cache configuration
let cachedMetrics: Record<string, string | null>[] | null = null;
let lastCacheTime = 0;
const CACHE_DURATION = 3600000; // 1 hour in milliseconds

/**
 * Parse CSV content to JSON array
 * Handles basic CSV format (no quoted fields with commas)
 */
function parseCSV(csvContent: string): Record<string, string | null>[] {
  const lines = csvContent.trim().split("\n");
  if (lines.length < 2) return [];

  const headers = lines[0].split(",").map(h => h.trim());

  return lines.slice(1).map((line) => {
    const values = line.split(",");
    const obj: Record<string, string | null> = {};
    headers.forEach((header, index) => {
      obj[header] = values[index]?.trim() || null;
    });
    return obj;
  });
}

/**
 * GET /api/reforms/metrics
 * Serve pre-computed reform impact metrics from Python data pipeline
 * Includes 1-hour caching for improved performance
 */
export async function GET() {
  const now = Date.now();

  // Return cached data if still valid
  if (cachedMetrics && (now - lastCacheTime < CACHE_DURATION)) {
    return NextResponse.json({
      success: true,
      data: cachedMetrics,
      count: cachedMetrics.length,
      source: "cached",
      cacheAge: Math.round((now - lastCacheTime) / 1000),
    });
  }

  try {
    // Path to the metrics file generated by Python pipeline
    const metricsPath = path.join(
      process.cwd(),
      "..",
      "data",
      "outputs",
      "comprehensive_reform_metrics.csv"
    );

    // Check if file exists
    if (!existsSync(metricsPath)) {
      return NextResponse.json(
        {
          error: "Metrics file not found",
          message: `Expected file at: ${metricsPath}`,
        },
        { status: 404 }
      );
    }

    const csvContent = await readFile(metricsPath, "utf-8");

    // Validate content
    if (!csvContent || csvContent.trim().length === 0) {
      return NextResponse.json(
        {
          error: "Metrics file is empty",
        },
        { status: 400 }
      );
    }

    // Parse CSV to JSON
    const data = parseCSV(csvContent);

    if (data.length === 0) {
      return NextResponse.json(
        {
          error: "No valid reform metrics found in file",
        },
        { status: 400 }
      );
    }

    // Update cache
    cachedMetrics = data;
    lastCacheTime = now;

    return NextResponse.json({
      success: true,
      data,
      count: data.length,
      source: "fresh",
    });
  } catch (error) {
    console.error("Error reading reform metrics:", error);
    return NextResponse.json(
      {
        error: "Failed to load reform metrics",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
