import { NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";

/**
 * GET /api/reforms/metrics
 * Serve pre-computed reform impact metrics from Python data pipeline
 */
export async function GET() {
  try {
    // Path to the metrics file generated by Python pipeline
    const metricsPath = path.join(
      process.cwd(),
      "..",
      "data",
      "outputs",
      "comprehensive_reform_metrics.csv"
    );

    const csvContent = await readFile(metricsPath, "utf-8");

    // Parse CSV to JSON (simple parser)
    const lines = csvContent.trim().split("\n");
    const headers = lines[0].split(",");

    const data = lines.slice(1).map((line) => {
      const values = line.split(",");
      const obj: any = {};
      headers.forEach((header, index) => {
        obj[header.trim()] = values[index]?.trim() || null;
      });
      return obj;
    });

    return NextResponse.json({
      success: true,
      data,
      count: data.length,
      source: "python_pipeline",
    });
  } catch (error) {
    console.error("Error reading reform metrics:", error);
    return NextResponse.json(
      {
        error: "Failed to load reform metrics",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
