import { NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";
import { createAPITimer, performanceStore } from "@/lib/performance";

// In-memory cache for reform metrics
let metricsCache: { data: any; timestamp: number } | null = null;
const CACHE_TTL = 3600000; // 1 hour

/**
 * GET /api/reforms/metrics
 * Serve pre-computed reform impact metrics from Python data pipeline
 */
export async function GET() {
  const timer = createAPITimer();

  try {
    // Check cache first
    if (metricsCache && Date.now() - metricsCache.timestamp < CACHE_TTL) {
      const response = NextResponse.json({
        success: true,
        data: metricsCache.data,
        count: metricsCache.data.length,
        source: "python_pipeline",
        cached: true,
      });

      timer.addHeader(response.headers);
      performanceStore.addAPIMetric({
        endpoint: '/api/reforms/metrics',
        method: 'GET',
        duration: timer.elapsed(),
        status: 200,
        timestamp: Date.now(),
      });

      return response;
    }

    // Path to the metrics file generated by Python pipeline
    const metricsPath = path.join(
      process.cwd(),
      "..",
      "data",
      "outputs",
      "comprehensive_reform_metrics.csv"
    );

    const csvContent = await readFile(metricsPath, "utf-8");

    // Parse CSV to JSON (simple parser)
    const lines = csvContent.trim().split("\n");
    const headers = lines[0].split(",");

    const data = lines.slice(1).map((line) => {
      const values = line.split(",");
      const obj: Record<string, string | null> = {};
      headers.forEach((header, index) => {
        obj[header.trim()] = values[index]?.trim() || null;
      });
      return obj;
    });

    // Update cache
    metricsCache = { data, timestamp: Date.now() };

    const response = NextResponse.json({
      success: true,
      data,
      count: data.length,
      source: "python_pipeline",
    });

    timer.addHeader(response.headers);
    performanceStore.addAPIMetric({
      endpoint: '/api/reforms/metrics',
      method: 'GET',
      duration: timer.elapsed(),
      status: 200,
      timestamp: Date.now(),
    });

    return response;
  } catch (error) {
    console.error("Error reading reform metrics:", error);

    performanceStore.addAPIMetric({
      endpoint: '/api/reforms/metrics',
      method: 'GET',
      duration: timer.elapsed(),
      status: 500,
      timestamp: Date.now(),
    });

    return NextResponse.json(
      {
        error: "Failed to load reform metrics",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
