import { NextResponse } from "next/server";
import { readFile } from "fs/promises";
import path from "path";

/**
 * GET /api/causal-analysis/did
 * Returns Difference-in-Differences causal analysis results
 *
 * Query parameters:
 * - reform_type (optional): Filter to specific reform type
 * - adoption_year (optional): Filter to specific year
 */
export async function GET(request: Request) {
  try {
    // Path to the DiD results file generated by Python pipeline
    const resultsPath = path.join(
      process.cwd(),
      "..",
      "data",
      "outputs",
      "did_analysis_results.json"
    );

    const jsonContent = await readFile(resultsPath, "utf-8");
    const data = JSON.parse(jsonContent);

    // Parse query parameters
    const { searchParams } = new URL(request.url);
    const reformType = searchParams.get("reform_type");
    const adoptionYear = searchParams.get("adoption_year");

    // Filter results if parameters provided
    let filteredResults = data.all_results || [];

    if (reformType && reformType !== "__ALL__") {
      filteredResults = filteredResults.filter(
        (r: any) => r.reform_type === reformType
      );
    }

    if (adoptionYear) {
      const year = parseInt(adoptionYear);
      if (!isNaN(year)) {
        filteredResults = filteredResults.filter(
          (r: any) => r.adoption_year === year
        );
      }
    }

    // Calculate summary for filtered results
    const significant = filteredResults.filter((r: any) => r.p_value < 0.05);
    const positive = filteredResults.filter((r: any) => r.treatment_effect > 0);
    const avgEffect = filteredResults.length > 0
      ? filteredResults.reduce((sum: number, r: any) => sum + r.treatment_effect, 0) / filteredResults.length
      : 0;

    return NextResponse.json({
      success: true,
      metadata: data.metadata,
      results: filteredResults,
      summary: {
        total_analyses: filteredResults.length,
        significant_effects: significant.length,
        positive_effects: positive.length,
        average_effect: Math.round(avgEffect * 100) / 100,
        confidence: data.summary?.confidence || "unknown",
      },
      reform_analyses: data.reform_analyses || [],
      global_summary: data.summary,
    });
  } catch (error) {
    console.error("Error reading DiD analysis results:", error);
    return NextResponse.json(
      {
        error: "Failed to load DiD analysis results",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
